// Generated by BUCKLESCRIPT VERSION 5.0.0, PLEASE EDIT WITH CARE
'use strict';

var Commander = require("commander");

function make(param) {
  return Commander;
}

var $$default = "commander";

exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
exports.make = make;
/* commander Not a pure module */
