// Generated by BUCKLESCRIPT VERSION 5.0.0, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Util$ThemeConverter = require("../src/Util.bs.js");

jest.mock("os", (function (param) {
        return {
                userInfo: (function (param) {
                    return {
                            username: "jest"
                          };
                  }),
                platform: (function (param) {
                    return "darwin";
                  })
              };
      }));

Jest.describe("Util", (function (param) {
        return Jest.describe("getSublimeTextPackageDir", (function (param) {
                      return Jest.test("should return the macOS path", (function (param) {
                                    return Jest.Expect[/* toBe */2]("/Users/jest/Library/Application Support/Sublime Text 3/Packages/", Jest.Expect[/* expect */0](Util$ThemeConverter.getSublimeTextPackageDir(/* () */0)));
                                  }));
                    }));
      }));

/*  Not a pure module */
